export global Icons {
    out property <image> add: @image-url("icons/add.svg");
    out property <image> remove: @image-url("icons/remove.svg");
    out property <image> check: @image-url("icons/check.svg");
    out property <image> close: @image-url("icons/close.svg");
    out property <image> backspace: @image-url("icons/backspace.svg");

    out property <image> arrow-upward: @image-url("icons/arrow_upward.svg");
    out property <image> arrow-downward: @image-url("icons/arrow_downward.svg");
    out property <image> thermostat: @image-url("icons/thermostat.svg");
    out property <image> co2: @image-url("icons/co2.svg");
    out property <image> water-drop: @image-url("icons/water_drop.svg");
    out property <image> local-fire-department: @image-url("icons/local_fire_department.svg");

    out property <image> schedule: @image-url("icons/schedule.svg");
    out property <image> settings: @image-url("icons/settings.svg");
    out property <image> factory: @image-url("icons/factory.svg");
    out property <image> history: @image-url("icons/history.svg");
    out property <image> dashboard: @image-url("icons/dashboard.svg");
    out property <image> home: @image-url("icons/home.svg");
    out property <image> menu: @image-url("icons/menu.svg");
    out property <image> list: @image-url("icons/list.svg");
    out property <image> grid-view: @image-url("icons/grid_view.svg");

    out property <image> warning: @image-url("icons/warning.svg");
    out property <image> error: @image-url("icons/error.svg");
    out property <image> info: @image-url("icons/info.svg");
    out property <image> notifications: @image-url("icons/notifications.svg");
    out property <image> lock: @image-url("icons/lock.svg");
    out property <image> mode-fan: @image-url("icons/mode_fan.svg");
    out property <image> check-circle: @image-url("icons/check.svg");
}

